url=https://automationexercise.com/
browser=chrome
chromedriver_file_location=D:\\Eclipse\\AutomationExercise\\src\\main\\java\\Drivers\\chromedriver.exe
firefiox_file_location=D:\\Eclipse\\AutomationExercise\\src\\main\\java\\Drivers\\geckodriver.exe
edge_file_location=D:\\Eclipse\\AutomationExercise\\src\\main\\java\\Drivers\\msedgedriver.exe